language: generic 
sudo: required
services:
	- docker

before_install:
	- docker build -t marradecki/docker-react -f Dockerfile.dev .
	
script:
	- docker run -e CI=true marradecki/docker-react npm run test -- --coverage
          
